name: Development CI Pipeline

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

permissions:
  contents: read
  actions: read

jobs:
  # Job 1: Code Quality & Testing
  quality:
    name: Code Quality & Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run TypeScript type check
      run: npm run type-check
      
    - name: Run ESLint
      run: npm run lint
      
    - name: Run tests
      run: npm run test:no-e2e
      
    - name: Build application
      run: npm run build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: |
          .next/
          out/
        retention-days: 1

  # Job 2: Security Audit (Basic)
  security:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run security audit
      run: npm audit || echo "Audit completed with warnings"
      continue-on-error: true

  # Job 3: Development Summary
  dev-summary:
    name: Development Summary
    runs-on: ubuntu-latest
    needs: [quality, security]
    if: always()
    
    steps:
    - name: Development Status
      run: |
        echo "Development CI Pipeline Results:"
        echo "Code Quality: ${{ needs.quality.result }}"
        echo "Security Audit: ${{ needs.security.result }}"
        
        if [[ "${{ needs.quality.result }}" == "success" ]]; then
          echo "Code quality checks passed"
        else
          echo "Code quality issues found"
        fi
        
        echo "Ready for continued development"